### 请用 VSCODE 打开


###
POST https://localhost:5001/api/Libra HTTP/1.1
Content-Type:application/json

{
    "Caller":"TeacherService.Hello1",
    "Parameters":"a"
}

###
GET https://localhost:6001/api/Test/1 HTTP/1.1
###
GET https://localhost:6001/api/Test/2 HTTP/1.1
###
GET https://localhost:6001/api/Test/3 HTTP/1.1
###
GET https://localhost:6001/api/Test/4 HTTP/1.1
###
GET https://localhost:6001/api/Test/5 HTTP/1.1
###
GET https://localhost:6001/api/Test/6 HTTP/1.1
###
GET https://localhost:6001/api/Test/7 HTTP/1.1
###
GET https://localhost:6001/api/Test/8 HTTP/1.1
###
GET https://localhost:6001/api/Test/9 HTTP/1.1


### 插件

### 装载插件
GET https://localhost:5001/api/Plugin/add HTTP/1.1
### 调用插件
GET https://localhost:6001/api/Test/10 HTTP/1.1
### 调用插件
GET https://localhost:6001/api/Test/11 HTTP/1.1
### 卸载插件
GET https://localhost:5001/api/Plugin/dispose HTTP/1.1


### 异步
GET https://localhost:6001/api/Test/12 HTTP/1.1
### 异步
GET https://localhost:6001/api/Test/13 HTTP/1.1
### 数组
GET https://localhost:6001/api/Test/14 HTTP/1.1
### 空结果
GET https://localhost:6001/api/Test/15 HTTP/1.1
### 非空结果
GET https://localhost:6001/api/Test/16 HTTP/1.1
### 组播
GET https://localhost:6001/api/Test/17 HTTP/1.1
### 组播
GET https://localhost:6001/api/Test/18 HTTP/1.1
### 组播
GET https://localhost:6001/api/Test/19 HTTP/1.1
### 组播通知
GET https://localhost:6001/api/Test/20 HTTP/1.1
### 组播通知
GET https://localhost:6001/api/Test/21 HTTP/1.1
